"""Minimal LangGraph travel planner skeleton."""

import re
from typing import TypedDict

from langgraph.graph import END, START, StateGraph

from src.app.models.trip import TripDay, TripPlanRequest, TripPlanResponse


class TripPlannerState(TypedDict, total=False):
    """State passed through the trip planner graph."""

    request: TripPlanRequest
    plan: TripPlanResponse


_STYLE_THEMES: dict[str, tuple[str, str]] = {
    "culture": ("Temples, neighborhoods, and local stories", "historic district"),
    "food": ("Markets, cafes, and local kitchens", "food street"),
    "nature": ("Scenic walks and quiet outdoor time", "park or viewpoint"),
    "family": ("Easy pacing and family-friendly stops", "hands-on museum"),
    "romantic": ("Slow walks and atmospheric evenings", "riverside walk"),
    "adventure": ("Active days and memorable detours", "trail or day trip"),
    "relaxed": ("Unhurried days with room to wander", "local neighborhood"),
}


def plan_trip_with_graph(request: TripPlanRequest) -> TripPlanResponse:
    """Run the local LangGraph planner and return its generated trip plan."""

    final_state = _trip_planner_graph.invoke({"request": request})
    return final_state["plan"]


def _build_graph():
    graph = StateGraph(TripPlannerState)
    graph.add_node("draft_itinerary", _draft_itinerary)
    graph.add_edge(START, "draft_itinerary")
    graph.add_edge("draft_itinerary", END)
    return graph.compile()


def _draft_itinerary(state: TripPlannerState) -> TripPlannerState:
    request = state["request"]
    return {"request": request, "plan": _build_demo_plan(request)}


def _build_demo_plan(request: TripPlanRequest) -> TripPlanResponse:
    style_theme, anchor_place = _STYLE_THEMES[request.travel_style]
    slug = _slugify(request.destination)
    month_phrase = f" in {request.month}" if request.month else ""
    origin_phrase = f" from {request.origin}" if request.origin else ""
    notes_phrase = " It leaves space for your notes and preferences." if request.notes else ""

    days = [
        _build_day_plan(
            day=day,
            destination=request.destination,
            style_theme=style_theme,
            anchor_place=anchor_place,
        )
        for day in range(1, request.days + 1)
    ]

    return TripPlanResponse(
        trip_id=f"demo-{slug}-{request.days}",
        destination=request.destination,
        summary=(
            f"A {request.days}-day {request.travel_style}-focused plan for "
            f"{request.destination}{month_phrase}{origin_phrase}, built with compact days "
            f"and practical pacing.{notes_phrase}"
        ),
        days=days,
        tips=[
            "Group nearby sights together to avoid transit fatigue.",
            "Keep one flexible block each day for weather, rest, or discoveries.",
            _budget_tip(request.budget),
        ],
        disclaimer="Demo itinerary generated by the local LangGraph placeholder.",
    )


def _build_day_plan(
    *,
    day: int,
    destination: str,
    style_theme: str,
    anchor_place: str,
) -> TripDay:
    if day == 1:
        return TripDay(
            day=day,
            title="Arrival and first walk",
            theme="Settle in",
            morning=f"Arrive in {destination}, check in, and take a short orientation walk.",
            afternoon=f"Visit a nearby {anchor_place} to get a first sense of the city.",
            evening="Choose an easy local dinner near your stay.",
            notes=["Keep the first day light.", style_theme],
        )

    return TripDay(
        day=day,
        title=f"Day {day} route cluster",
        theme=style_theme,
        morning=f"Start with a focused visit around a well-connected area of {destination}.",
        afternoon=f"Continue to a nearby {anchor_place}, then leave time for a cafe or rest stop.",
        evening="End with dinner close to the final stop instead of crossing town again.",
        notes=["Avoid more than two major transit hops in one day."],
    )


def _budget_tip(budget: str) -> str:
    if budget == "low":
        return "Use casual meals, public transit, and free viewpoints to keep costs controlled."
    if budget == "high":
        return "Reserve one premium meal or private guided experience where it adds the most value."
    return "Mix casual meals with one or two planned splurges for balance."


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "trip"


_trip_planner_graph = _build_graph()
